CREATE SCHEMA `user_type`;

CREATE TABLE `user_id_pwd` (
  `seq_no` int AUTO_INCREMENT,
  `user_id` varchar(255) PRIMARY KEY,
  `password` varchar(255) NOT NULL
);

CREATE TABLE `user_table` (
  `user_id` varchar(255) PRIMARY KEY,
  `fname` varchar(255) NOT NULL,
  `mname` varchar(255),
  `lname` varchar(255),
  `dob` datetime NOT NULL,
  `address` varchar(255),
  `city` varchar(255) NOT NULL,
  `profession` varchar(255) NOT NULL DEFAULT "NOT PROVIDED",
  `member_type` ENUM ('initial', 'starter', 'pro', 'admin')
);

CREATE TABLE `user_post_and_follower_info` (
  `user_id` varchar[pk],
  `num_followers` integer NOT NULL DEFAULT 0,
  `num_following` integer NOT NULL DEFAULT 0,
  `num_post` integer NOT NULL DEFAULT 0
);

CREATE TABLE `post_id` (
  `post_id` varchar(255) PRIMARY KEY COMMENT 'Post id will be generated by some algorithm',
  `user_id` varchar(255) NOT NULL
);

CREATE TABLE `post_details` (
  `post_id` varchar(255) PRIMARY KEY,
  `title` varchar(255) COMMENT 'upto 256 char you can put',
  `caption` varchar(255) COMMENT 'This will store upto 1024characters',
  `image_url` varchar(1024) COMMENT 'This will store absolute path of image',
  `time_stamp` timedate COMMENT 'For time stamp of post'
);

CREATE TABLE `user_follower` (
  `user_id` varchar(255),
  `follower_id` varchar(255)
);

CREATE TABLE `user_following` (
  `user_id` varchar(255),
  `following_id` varchar(255)
);

ALTER TABLE `user_id_pwd` COMMENT = 'It will store id password of user';

ALTER TABLE `user_table` COMMENT = 'it store all fundametal details of user';

ALTER TABLE `user_post_and_follower_info` COMMENT = 'this will store number of followers and number of posts';

ALTER TABLE `post_id` COMMENT = 'This will store post id with corresponding userid';

ALTER TABLE `post_details` COMMENT = 'This table will store complete post details';

ALTER TABLE `user_follower` COMMENT = 'this will store all users follower and following list';

ALTER TABLE `user_following` COMMENT = ' this will store all user following list';

ALTER TABLE `user_id_pwd` ADD FOREIGN KEY (`user_id`) REFERENCES `user_post_and_follower_info` (`user_id`);

ALTER TABLE `user_id_pwd` ADD FOREIGN KEY (`user_id`) REFERENCES `user_table` (`user_id`) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE `post_id` ADD FOREIGN KEY (`user_id`) REFERENCES `user_id_pwd` (`user_id`);

ALTER TABLE `post_details` ADD FOREIGN KEY (`post_id`) REFERENCES `post_id` (`post_id`);

ALTER TABLE `user_follower` ADD FOREIGN KEY (`user_id`) REFERENCES `user_id_pwd` (`user_id`);

ALTER TABLE `user_follower` ADD FOREIGN KEY (`follower_id`) REFERENCES `user_id_pwd` (`user_id`);

ALTER TABLE `user_following` ADD FOREIGN KEY (`user_id`) REFERENCES `user_id_pwd` (`user_id`);

ALTER TABLE `user_following` ADD FOREIGN KEY (`following_id`) REFERENCES `user_id_pwd` (`user_id`);
