CREATE SCHEMA "user_type";

CREATE TYPE "user_type"."member_type" AS ENUM (
  'initial',
  'starter',
  'pro',
  'admin'
);

CREATE TABLE "user_id_pwd" (
  "seq_no" SERIAL,
  "user_id" varchar PRIMARY KEY,
  "password" varchar NOT NULL
);

CREATE TABLE "user_table" (
  "user_id" varchar PRIMARY KEY,
  "fname" varchar NOT NULL,
  "mname" varchar,
  "lname" varchar,
  "dob" timestamp NOT NULL,
  "address" varchar,
  "city" varchar NOT NULL,
  "profession" varchar NOT NULL DEFAULT 'NOT PROVIDED',
  "member_type" user_type.member_type
);

CREATE TABLE "user_post_and_follower_info" (
  "user_id" varchar PRIMARY KEY,
  "num_followers" integer NOT NULL DEFAULT 0,
  "num_following" integer NOT NULL DEFAULT 0,
  "num_post" integer NOT NULL DEFAULT 0
);

CREATE TABLE "post_id" (
  "post_id" varchar PRIMARY KEY,
  "user_id" varchar NOT NULL
);

CREATE TABLE "post_content" (
  "post_id" varchar PRIMARY KEY,
  "title" varchar,
  "caption" varchar(255),
  "image_url" varchar(1024),
  "time_stamp" timedate
);

CREATE TABLE "user_followers" (
  "user_id" varchar,
  "follower_id" varchar
);

CREATE TABLE "user_followings" (
  "user_id" varchar,
  "following_id" varchar
);

CREATE TABLE "post_interation" (
  "post_id" varchar PRIMARY KEY,
  "likes" integer DEFAULT 0,
  "flags" integer DEFAULT 0,
  "comment_id" varchar UNIQUE NOT NULL
);

CREATE TABLE "post_comment_table" (
  "comment_id" varchar,
  "commenter_id" varchar,
  "comment_content" varchar(1024)
);

COMMENT ON TABLE "user_id_pwd" IS 'It will store id password of user';

COMMENT ON TABLE "user_table" IS 'it store all fundametal details of user';

COMMENT ON TABLE "user_post_and_follower_info" IS 'this will store number of followers and number of posts';

COMMENT ON TABLE "post_id" IS 'This will store post id with corresponding userid';

COMMENT ON COLUMN "post_id"."post_id" IS 'Post id will be generated by some algorithm';

COMMENT ON TABLE "post_content" IS 'This table will store complete post details';

COMMENT ON COLUMN "post_content"."title" IS 'upto 256 char you can put';

COMMENT ON COLUMN "post_content"."caption" IS 'This will store upto 1024characters';

COMMENT ON COLUMN "post_content"."image_url" IS 'This will store absolute path of image';

COMMENT ON COLUMN "post_content"."time_stamp" IS 'For time stamp of post';

COMMENT ON TABLE "user_followers" IS 'this will store all users follower and following list';

COMMENT ON TABLE "user_followings" IS ' this will store all user following list';

COMMENT ON TABLE "post_interation" IS 'This will store additional feature of a given post';

COMMENT ON COLUMN "post_interation"."likes" IS 'This will store number of likes in the post';

COMMENT ON COLUMN "post_interation"."flags" IS 'Flag basically number of dislikes on given post';

COMMENT ON COLUMN "post_interation"."comment_id" IS 'This 
                                      Will hold number of comments and all comments related stuff
  ';

COMMENT ON TABLE "post_comment_table" IS 'This will store all comments by the user on a given post and identified by a unique comment id';

ALTER TABLE "user_table" ADD FOREIGN KEY ("user_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "user_post_and_follower_info" ADD FOREIGN KEY ("user_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "post_id" ADD FOREIGN KEY ("user_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "post_content" ADD FOREIGN KEY ("post_id") REFERENCES "post_id" ("post_id");

ALTER TABLE "user_followers" ADD FOREIGN KEY ("user_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "user_followers" ADD FOREIGN KEY ("follower_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "user_followings" ADD FOREIGN KEY ("user_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "user_followings" ADD FOREIGN KEY ("following_id") REFERENCES "user_id_pwd" ("user_id");

ALTER TABLE "post_interation" ADD FOREIGN KEY ("post_id") REFERENCES "post_id" ("post_id");

ALTER TABLE "post_comment_table" ADD FOREIGN KEY ("comment_id") REFERENCES "post_interation" ("comment_id");

ALTER TABLE "post_comment_table" ADD FOREIGN KEY ("commenter_id") REFERENCES "user_id_pwd" ("user_id");
